package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class Card extends AttributeContainer implements KvmSerializable
{

    
    public String fullName;
    
    public String accountNumber;
    
    public BigInteger expirationMonth;
    
    public BigInteger expirationYear;
    
    public String cvIndicator;
    
    public String cvNumber;
    
    public String cardType;
    
    public String issueNumber;
    
    public BigInteger startMonth;
    
    public BigInteger startYear;
    
    public String pin;
    
    public String accountEncoderID;
    
    public String bin;
    
    public String encryptedData;
    
    public String suffix;
    
    public String prefix;
    
    public String cardTypeName;
    
    public String cardSubType;
    
    public String level2Eligible;
    
    public String level3Eligible;
    
    public String productCategory;
    
    public String crossBorderIndicator;
    
    public String billingCurrency;
    
    public String billingCurrencyNumericCode;
    
    public String billingCurrencyMinorDigits;
    
    public String octFastFundsIndicator;
    
    public String octBlockIndicator;
    
    public String onlineGamblingBlockIndicator;
    
    public String productName;
    
    public String usage;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("fullName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fullName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fullName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("accountNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.accountNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.accountNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("expirationMonth"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.expirationMonth = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.expirationMonth = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("expirationYear"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.expirationYear = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.expirationYear = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cvIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cvIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cvIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cvNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cvNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cvNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameCard"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cardType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cardType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("issueNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.issueNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.issueNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("startMonth"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.startMonth = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.startMonth = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("startYear"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.startYear = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.startYear = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("pin"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pin = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pin = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("accountEncoderID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.accountEncoderID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.accountEncoderID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("bin"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.bin = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.bin = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("encryptedData"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.encryptedData = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.encryptedData = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suffix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suffix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.suffix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("prefix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.prefix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.prefix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cardTypeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cardTypeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cardTypeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cardSubType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cardSubType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cardSubType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("level2Eligible"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.level2Eligible = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.level2Eligible = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("level3Eligible"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.level3Eligible = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.level3Eligible = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("productCategory"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.productCategory = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.productCategory = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("crossBorderIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.crossBorderIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.crossBorderIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("billingCurrency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.billingCurrency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.billingCurrency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("billingCurrencyNumericCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.billingCurrencyNumericCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.billingCurrencyNumericCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("billingCurrencyMinorDigits"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.billingCurrencyMinorDigits = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.billingCurrencyMinorDigits = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("octFastFundsIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.octFastFundsIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.octFastFundsIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("octBlockIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.octBlockIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.octBlockIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("onlineGamblingBlockIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.onlineGamblingBlockIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.onlineGamblingBlockIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("productName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.productName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.productName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("usage"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usage = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.fullName!=null?this.fullName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.accountNumber!=null?this.accountNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.expirationMonth!=null?this.expirationMonth.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.expirationYear!=null?this.expirationYear.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.cvIndicator!=null?this.cvIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.cvNumber!=null?this.cvNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.cardType!=null?this.cardType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.issueNumber!=null?this.issueNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.startMonth!=null?this.startMonth.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.startYear!=null?this.startYear.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.pin!=null?this.pin:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.accountEncoderID!=null?this.accountEncoderID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.bin!=null?this.bin:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.encryptedData!=null?this.encryptedData:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.suffix!=null?this.suffix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.prefix!=null?this.prefix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.cardTypeName!=null?this.cardTypeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.cardSubType!=null?this.cardSubType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.level2Eligible!=null?this.level2Eligible:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.level3Eligible!=null?this.level3Eligible:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.productCategory!=null?this.productCategory:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.crossBorderIndicator!=null?this.crossBorderIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.billingCurrency!=null?this.billingCurrency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.billingCurrencyNumericCode!=null?this.billingCurrencyNumericCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.billingCurrencyMinorDigits!=null?this.billingCurrencyMinorDigits:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.octFastFundsIndicator!=null?this.octFastFundsIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.octBlockIndicator!=null?this.octBlockIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.onlineGamblingBlockIndicator!=null?this.onlineGamblingBlockIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.productName!=null?this.productName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.usage!=null?this.usage:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 30;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fullName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "accountNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "expirationMonth";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "expirationYear";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cvIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cvNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameCard";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "issueNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "startMonth";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "startYear";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pin";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "accountEncoderID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "bin";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "encryptedData";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "suffix";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "prefix";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cardTypeName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cardSubType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "level2Eligible";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "level3Eligible";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "productCategory";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "crossBorderIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "billingCurrency";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "billingCurrencyNumericCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "billingCurrencyMinorDigits";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "octFastFundsIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "octBlockIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "onlineGamblingBlockIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "productName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usage";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

