package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class CCCreditService extends AttributeContainer implements KvmSerializable
{

    
    public String captureRequestID;
    
    public String reconciliationID;
    
    public String partialPaymentID;
    
    public String purchasingLevel;
    
    public String industryDatatype;
    
    public String commerceIndicator;
    
    public String billPayment;
    
    public String authorizationXID;
    
    public String occurrenceNumber;
    
    public String authCode;
    
    public String captureRequestToken;
    
    public String merchantReceiptNumber;
    
    public String checksumKey;
    
    public String aggregatorID;
    
    public String aggregatorName;
    
    public BigInteger duration;
    
    public BigInteger dpdeBillingMonth;
    
    public String reconciliationIDAlternate;
    
    public String refundReason;
    
    public String overridePaymentMethod;
    
    public String overridePaymentDetails;
    
    public String run;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("run"))
        {	
            java.lang.Object j = inObj.getAttribute("run");
            if (j != null)
            {
                run = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("captureRequestID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.captureRequestID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.captureRequestID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("reconciliationID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reconciliationID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.reconciliationID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("partialPaymentID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.partialPaymentID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.partialPaymentID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("purchasingLevel"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.purchasingLevel = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.purchasingLevel = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("industryDatatype"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.industryDatatype = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.industryDatatype = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("commerceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.commerceIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.commerceIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("billPayment"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.billPayment = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.billPayment = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authorizationXID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authorizationXID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authorizationXID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("occurrenceNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.occurrenceNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.occurrenceNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("captureRequestToken"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.captureRequestToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.captureRequestToken = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantReceiptNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantReceiptNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantReceiptNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("checksumKey"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.checksumKey = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.checksumKey = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("aggregatorID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.aggregatorID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.aggregatorID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("aggregatorName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.aggregatorName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.aggregatorName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("duration"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.duration = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.duration = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("dpdeBillingMonth"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dpdeBillingMonth = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.dpdeBillingMonth = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("reconciliationIDAlternate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reconciliationIDAlternate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.reconciliationIDAlternate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("refundReason"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.refundReason = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.refundReason = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("overridePaymentMethod"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.overridePaymentMethod = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.overridePaymentMethod = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("overridePaymentDetails"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.overridePaymentDetails = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.overridePaymentDetails = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.captureRequestID!=null?this.captureRequestID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.reconciliationID!=null?this.reconciliationID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.partialPaymentID!=null?this.partialPaymentID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.purchasingLevel!=null?this.purchasingLevel:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.industryDatatype!=null?this.industryDatatype:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.commerceIndicator!=null?this.commerceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.billPayment!=null?this.billPayment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.authorizationXID!=null?this.authorizationXID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.occurrenceNumber!=null?this.occurrenceNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.authCode!=null?this.authCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.captureRequestToken!=null?this.captureRequestToken:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.merchantReceiptNumber!=null?this.merchantReceiptNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.checksumKey!=null?this.checksumKey:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.aggregatorID!=null?this.aggregatorID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.aggregatorName!=null?this.aggregatorName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.duration!=null?this.duration.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.dpdeBillingMonth!=null?this.dpdeBillingMonth.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.reconciliationIDAlternate!=null?this.reconciliationIDAlternate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.refundReason!=null?this.refundReason:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.overridePaymentMethod!=null?this.overridePaymentMethod:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.overridePaymentDetails!=null?this.overridePaymentDetails:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 21;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "captureRequestID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reconciliationID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "partialPaymentID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "purchasingLevel";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "industryDatatype";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "commerceIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "billPayment";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authorizationXID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "occurrenceNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "captureRequestToken";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantReceiptNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "checksumKey";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "aggregatorID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "aggregatorName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "duration";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dpdeBillingMonth";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reconciliationIDAlternate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "refundReason";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "overridePaymentMethod";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "overridePaymentDetails";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "run";
            info.namespace= "";
            if(this.run!=null)
            {
                info.setValue(this.run);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

