package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class DAVReply extends AttributeContainer implements KvmSerializable
{

    
    public BigInteger reasonCode=BigInteger.ZERO;
    
    public String addressType;
    
    public String apartmentInfo;
    
    public String barCode;
    
    public String barCodeCheckDigit;
    
    public String careOf;
    
    public String cityInfo;
    
    public String countryInfo;
    
    public String directionalInfo;
    
    public String lvrInfo;
    
    public BigInteger matchScore;
    
    public String standardizedAddress1;
    
    public String standardizedAddress2;
    
    public String standardizedAddress3;
    
    public String standardizedAddress4;
    
    public String standardizedAddressNoApt;
    
    public String standardizedCity;
    
    public String standardizedCounty;
    
    public String standardizedCSP;
    
    public String standardizedState;
    
    public String standardizedPostalCode;
    
    public String standardizedCountry;
    
    public String standardizedISOCountry;
    
    public String stateInfo;
    
    public String streetInfo;
    
    public String suffixInfo;
    
    public String postalCodeInfo;
    
    public String overallInfo;
    
    public String usInfo;
    
    public String caInfo;
    
    public String intlInfo;
    
    public String usErrorInfo;
    
    public String caErrorInfo;
    
    public String intlErrorInfo;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("reasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reasonCode = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.reasonCode = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.addressType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.addressType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("apartmentInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.apartmentInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.apartmentInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("barCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.barCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.barCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("barCodeCheckDigit"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.barCodeCheckDigit = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.barCodeCheckDigit = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("careOf"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.careOf = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.careOf = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cityInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cityInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cityInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("countryInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.countryInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.countryInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("directionalInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.directionalInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.directionalInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("lvrInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lvrInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lvrInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("matchScore"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.matchScore = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.matchScore = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedAddress1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedAddress1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedAddress1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedAddress2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedAddress2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedAddress2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedAddress3"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedAddress3 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedAddress3 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedAddress4"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedAddress4 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedAddress4 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedAddressNoApt"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedAddressNoApt = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedAddressNoApt = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedCity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedCity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedCity = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedCounty"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedCounty = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedCounty = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedCSP"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedCSP = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedCSP = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedState"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedState = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedState = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedPostalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedPostalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("standardizedISOCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.standardizedISOCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.standardizedISOCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("stateInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.stateInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.stateInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("streetInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.streetInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.streetInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suffixInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suffixInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.suffixInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("postalCodeInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.postalCodeInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.postalCodeInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("overallInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.overallInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.overallInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("usInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("caInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.caInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.caInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("intlInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.intlInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.intlInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("usErrorInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.usErrorInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.usErrorInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("caErrorInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.caErrorInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.caErrorInfo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("intlErrorInfo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.intlErrorInfo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.intlErrorInfo = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.reasonCode!=null?this.reasonCode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.addressType!=null?this.addressType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.apartmentInfo!=null?this.apartmentInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.barCode!=null?this.barCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.barCodeCheckDigit!=null?this.barCodeCheckDigit:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.careOf!=null?this.careOf:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.cityInfo!=null?this.cityInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.countryInfo!=null?this.countryInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.directionalInfo!=null?this.directionalInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.lvrInfo!=null?this.lvrInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.matchScore!=null?this.matchScore.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.standardizedAddress1!=null?this.standardizedAddress1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.standardizedAddress2!=null?this.standardizedAddress2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.standardizedAddress3!=null?this.standardizedAddress3:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.standardizedAddress4!=null?this.standardizedAddress4:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.standardizedAddressNoApt!=null?this.standardizedAddressNoApt:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.standardizedCity!=null?this.standardizedCity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.standardizedCounty!=null?this.standardizedCounty:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.standardizedCSP!=null?this.standardizedCSP:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.standardizedState!=null?this.standardizedState:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.standardizedPostalCode!=null?this.standardizedPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.standardizedCountry!=null?this.standardizedCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.standardizedISOCountry!=null?this.standardizedISOCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.stateInfo!=null?this.stateInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.streetInfo!=null?this.streetInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.suffixInfo!=null?this.suffixInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.postalCodeInfo!=null?this.postalCodeInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.overallInfo!=null?this.overallInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.usInfo!=null?this.usInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.caInfo!=null?this.caInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.intlInfo!=null?this.intlInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.usErrorInfo!=null?this.usErrorInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.caErrorInfo!=null?this.caErrorInfo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==33)
        {
            return this.intlErrorInfo!=null?this.intlErrorInfo:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 34;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reasonCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "addressType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "apartmentInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "barCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "barCodeCheckDigit";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "careOf";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cityInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "countryInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "directionalInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lvrInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "matchScore";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedAddress1";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedAddress2";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedAddress3";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedAddress4";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedAddressNoApt";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedCity";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedCounty";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedCSP";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedState";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedPostalCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "standardizedISOCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "stateInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "streetInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "suffixInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "postalCodeInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "overallInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "caInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "intlInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "usErrorInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "caErrorInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "intlErrorInfo";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

