package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class DecisionManagerTravelData extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< DecisionManagerTravelLeg> leg =new ArrayList<DecisionManagerTravelLeg >();
    
    public String departureDateTime;
    
    public String completeRoute;
    
    public String journeyType;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("leg"))
        {
            if(obj!=null)
            {
                if(this.leg==null)
                {
                    this.leg = new java.util.ArrayList< DecisionManagerTravelLeg>();
                }
                java.lang.Object j =obj;
                DecisionManagerTravelLeg j1= (DecisionManagerTravelLeg)__envelope.get(j,DecisionManagerTravelLeg.class,false);
                this.leg.add(j1);
            }
            return true;
        }
        if (info.name.equals("departureDateTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.departureDateTime = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.departureDateTime = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("completeRoute"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.completeRoute = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.completeRoute = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("journeyType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.journeyType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.journeyType = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.leg.size())
        {
            java.lang.Object leg = this.leg.get(propertyIndex-(0));
            return leg!=null?leg:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==0+this.leg.size())
        {
            return this.departureDateTime!=null?this.departureDateTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1+this.leg.size())
        {
            return this.completeRoute!=null?this.completeRoute:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2+this.leg.size())
        {
            return this.journeyType!=null?this.journeyType:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+leg.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.leg.size())
        {
            info.type = DecisionManagerTravelLeg.class;
            info.name = "leg";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==0+this.leg.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "departureDateTime";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1+this.leg.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "completeRoute";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2+this.leg.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "journeyType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

