package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class InvoiceHeader extends AttributeContainer implements KvmSerializable
{

    
    public String merchantDescriptor;
    
    public String merchantDescriptorContact;
    
    public String merchantDescriptorAlternate;
    
    public String merchantDescriptorStreet;
    
    public String merchantDescriptorCity;
    
    public String merchantDescriptorState;
    
    public String merchantDescriptorPostalCode;
    
    public String merchantDescriptorCountry;
    
    public String isGift;
    
    public String returnsAccepted;
    
    public String tenderType;
    
    public String merchantVATRegistrationNumber;
    
    public String purchaserOrderDate;
    
    public String purchaserVATRegistrationNumber;
    
    public String vatInvoiceReferenceNumber;
    
    public String summaryCommodityCode;
    
    public String supplierOrderReference;
    
    public String userPO;
    
    public String costCenter;
    
    public String purchaserCode;
    
    public String taxable;
    
    public String amexDataTAA1;
    
    public String amexDataTAA2;
    
    public String amexDataTAA3;
    
    public String amexDataTAA4;
    
    public String invoiceDate;
    
    public String totalTaxTypeCode;
    
    public String cardAcceptorRefNumber;
    
    public String authorizedContactName;
    
    public String businessApplicationID;
    
    public BigInteger salesOrganizationID;
    
    public String submerchantID;
    
    public String submerchantName;
    
    public String submerchantStreet;
    
    public String submerchantCity;
    
    public String submerchantPostalCode;
    
    public String submerchantState;
    
    public String submerchantCountry;
    
    public String submerchantEmail;
    
    public String submerchantTelephoneNumber;
    
    public String submerchantRegion;
    
    public String submerchantMerchantID;
    
    public String merchantDescriptorCounty;
    
    public String referenceDataCode;
    
    public String referenceDataNumber;
    
    public String merchantDescriptorStoreID;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("merchantDescriptor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptor = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptor = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorContact"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorContact = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorContact = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorAlternate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorAlternate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorAlternate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorStreet"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorStreet = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorStreet = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorCity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorCity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorCity = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorState"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorState = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorState = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorPostalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorPostalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("isGift"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.isGift = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.isGift = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("returnsAccepted"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.returnsAccepted = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.returnsAccepted = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("tenderType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.tenderType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.tenderType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantVATRegistrationNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantVATRegistrationNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantVATRegistrationNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("purchaserOrderDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.purchaserOrderDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.purchaserOrderDate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("purchaserVATRegistrationNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.purchaserVATRegistrationNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.purchaserVATRegistrationNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("vatInvoiceReferenceNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.vatInvoiceReferenceNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.vatInvoiceReferenceNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("summaryCommodityCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.summaryCommodityCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.summaryCommodityCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("supplierOrderReference"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.supplierOrderReference = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.supplierOrderReference = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("userPO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.userPO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.userPO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("costCenter"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.costCenter = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.costCenter = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("purchaserCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.purchaserCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.purchaserCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("taxable"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.taxable = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.taxable = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("amexDataTAA1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.amexDataTAA1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.amexDataTAA1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("amexDataTAA2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.amexDataTAA2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.amexDataTAA2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("amexDataTAA3"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.amexDataTAA3 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.amexDataTAA3 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("amexDataTAA4"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.amexDataTAA4 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.amexDataTAA4 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("invoiceDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.invoiceDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.invoiceDate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("totalTaxTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.totalTaxTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.totalTaxTypeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cardAcceptorRefNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cardAcceptorRefNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cardAcceptorRefNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authorizedContactName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authorizedContactName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authorizedContactName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("businessApplicationID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.businessApplicationID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.businessApplicationID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("salesOrganizationID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.salesOrganizationID = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.salesOrganizationID = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantStreet"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantStreet = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantStreet = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantCity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantCity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantCity = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantPostalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantPostalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantState"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantState = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantState = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantEmail"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantEmail = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantEmail = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantTelephoneNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantTelephoneNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantTelephoneNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantRegion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantRegion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantRegion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("submerchantMerchantID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.submerchantMerchantID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.submerchantMerchantID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorCounty"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorCounty = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorCounty = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("referenceDataCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.referenceDataCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.referenceDataCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("referenceDataNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.referenceDataNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.referenceDataNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("merchantDescriptorStoreID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.merchantDescriptorStoreID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.merchantDescriptorStoreID = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.merchantDescriptor!=null?this.merchantDescriptor:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.merchantDescriptorContact!=null?this.merchantDescriptorContact:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.merchantDescriptorAlternate!=null?this.merchantDescriptorAlternate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.merchantDescriptorStreet!=null?this.merchantDescriptorStreet:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.merchantDescriptorCity!=null?this.merchantDescriptorCity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.merchantDescriptorState!=null?this.merchantDescriptorState:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.merchantDescriptorPostalCode!=null?this.merchantDescriptorPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.merchantDescriptorCountry!=null?this.merchantDescriptorCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.isGift!=null?this.isGift:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.returnsAccepted!=null?this.returnsAccepted:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.tenderType!=null?this.tenderType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.merchantVATRegistrationNumber!=null?this.merchantVATRegistrationNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.purchaserOrderDate!=null?this.purchaserOrderDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.purchaserVATRegistrationNumber!=null?this.purchaserVATRegistrationNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.vatInvoiceReferenceNumber!=null?this.vatInvoiceReferenceNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.summaryCommodityCode!=null?this.summaryCommodityCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.supplierOrderReference!=null?this.supplierOrderReference:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.userPO!=null?this.userPO:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.costCenter!=null?this.costCenter:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.purchaserCode!=null?this.purchaserCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.taxable!=null?this.taxable:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.amexDataTAA1!=null?this.amexDataTAA1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.amexDataTAA2!=null?this.amexDataTAA2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.amexDataTAA3!=null?this.amexDataTAA3:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.amexDataTAA4!=null?this.amexDataTAA4:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.invoiceDate!=null?this.invoiceDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.totalTaxTypeCode!=null?this.totalTaxTypeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.cardAcceptorRefNumber!=null?this.cardAcceptorRefNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.authorizedContactName!=null?this.authorizedContactName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.businessApplicationID!=null?this.businessApplicationID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.salesOrganizationID!=null?this.salesOrganizationID.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.submerchantID!=null?this.submerchantID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.submerchantName!=null?this.submerchantName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==33)
        {
            return this.submerchantStreet!=null?this.submerchantStreet:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==34)
        {
            return this.submerchantCity!=null?this.submerchantCity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==35)
        {
            return this.submerchantPostalCode!=null?this.submerchantPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==36)
        {
            return this.submerchantState!=null?this.submerchantState:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==37)
        {
            return this.submerchantCountry!=null?this.submerchantCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==38)
        {
            return this.submerchantEmail!=null?this.submerchantEmail:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==39)
        {
            return this.submerchantTelephoneNumber!=null?this.submerchantTelephoneNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==40)
        {
            return this.submerchantRegion!=null?this.submerchantRegion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==41)
        {
            return this.submerchantMerchantID!=null?this.submerchantMerchantID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==42)
        {
            return this.merchantDescriptorCounty!=null?this.merchantDescriptorCounty:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==43)
        {
            return this.referenceDataCode!=null?this.referenceDataCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==44)
        {
            return this.referenceDataNumber!=null?this.referenceDataNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==45)
        {
            return this.merchantDescriptorStoreID!=null?this.merchantDescriptorStoreID:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 46;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptor";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorContact";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorAlternate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorStreet";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorCity";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorState";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorPostalCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "isGift";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "returnsAccepted";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "tenderType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantVATRegistrationNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "purchaserOrderDate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "purchaserVATRegistrationNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "vatInvoiceReferenceNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "summaryCommodityCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "supplierOrderReference";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "userPO";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "costCenter";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "purchaserCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "taxable";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "amexDataTAA1";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "amexDataTAA2";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "amexDataTAA3";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "amexDataTAA4";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "invoiceDate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "totalTaxTypeCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cardAcceptorRefNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authorizedContactName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "businessApplicationID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "salesOrganizationID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantStreet";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantCity";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==35)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantPostalCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==36)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantState";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==37)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==38)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantEmail";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==39)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantTelephoneNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==40)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantRegion";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==41)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "submerchantMerchantID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==42)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorCounty";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==43)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "referenceDataCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==44)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "referenceDataNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==45)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "merchantDescriptorStoreID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

