package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class Leg extends AttributeContainer implements KvmSerializable
{

    
    public String carrierCode;
    
    public String flightNumber;
    
    public String originatingAirportCode;
    
    public String _class;
    
    public String stopoverCode;
    
    public String departureDate;
    
    public String destination;
    
    public String fareBasis;
    
    public String departTax;
    
    public String conjunctionTicket;
    
    public String exchangeTicket;
    
    public String couponNumber;
    
    public String departureTime;
    
    public String departureTimeSegment;
    
    public String arrivalTime;
    
    public String arrivalTimeSegment;
    
    public String endorsementsRestrictions;
    
    public String fare;
    
    public String fee;
    
    public String tax;
    
    public BigInteger id=BigInteger.ZERO;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("id"))
        {	
            java.lang.Object j = inObj.getAttribute("id");
            if (j != null)
            {
                id = new BigInteger(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("carrierCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.carrierCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.carrierCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("flightNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.flightNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.flightNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("originatingAirportCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.originatingAirportCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.originatingAirportCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("class"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this._class = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this._class = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("stopoverCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.stopoverCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.stopoverCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("departureDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.departureDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.departureDate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("destination"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.destination = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.destination = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("fareBasis"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fareBasis = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fareBasis = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("departTax"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.departTax = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.departTax = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("conjunctionTicket"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.conjunctionTicket = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.conjunctionTicket = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("exchangeTicket"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.exchangeTicket = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.exchangeTicket = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("couponNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.couponNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.couponNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("departureTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.departureTime = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.departureTime = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("departureTimeSegment"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.departureTimeSegment = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.departureTimeSegment = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("arrivalTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.arrivalTime = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.arrivalTime = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("arrivalTimeSegment"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.arrivalTimeSegment = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.arrivalTimeSegment = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("endorsementsRestrictions"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.endorsementsRestrictions = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.endorsementsRestrictions = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("fare"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fare = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fare = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("fee"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.fee = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.fee = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("tax"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.tax = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.tax = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.carrierCode!=null?this.carrierCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.flightNumber!=null?this.flightNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.originatingAirportCode!=null?this.originatingAirportCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this._class!=null?this._class:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.stopoverCode!=null?this.stopoverCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.departureDate!=null?this.departureDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.destination!=null?this.destination:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.fareBasis!=null?this.fareBasis:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.departTax!=null?this.departTax:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.conjunctionTicket!=null?this.conjunctionTicket:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.exchangeTicket!=null?this.exchangeTicket:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.couponNumber!=null?this.couponNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.departureTime!=null?this.departureTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.departureTimeSegment!=null?this.departureTimeSegment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.arrivalTime!=null?this.arrivalTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.arrivalTimeSegment!=null?this.arrivalTimeSegment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.endorsementsRestrictions!=null?this.endorsementsRestrictions:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.fare!=null?this.fare:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.fee!=null?this.fee:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.tax!=null?this.tax:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 20;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "carrierCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "flightNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "originatingAirportCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "class";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "stopoverCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "departureDate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "destination";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fareBasis";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "departTax";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "conjunctionTicket";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "exchangeTicket";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "couponNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "departureTime";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "departureTimeSegment";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "arrivalTime";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "arrivalTimeSegment";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "endorsementsRestrictions";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fare";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fee";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "tax";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "id";
            info.namespace= "";
            if(this.id!=null)
            {
                info.setValue(this.id);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

