package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class Network extends AttributeContainer implements KvmSerializable
{

    
    public String octDomesticIndicator;
    
    public String octCrossBorderIndicator;
    
    public String aftDomesticIndicator;
    
    public String aftCrossBorderIndicator;
    
    public String networkID;
    
    public String networkOrder;
    
    public BigInteger id;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("id"))
        {	
            java.lang.Object j = inObj.getAttribute("id");
            if (j != null)
            {
                id = new BigInteger(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("octDomesticIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.octDomesticIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.octDomesticIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("octCrossBorderIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.octCrossBorderIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.octCrossBorderIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("aftDomesticIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.aftDomesticIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.aftDomesticIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("aftCrossBorderIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.aftCrossBorderIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.aftCrossBorderIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("networkID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.networkID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.networkID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("networkOrder"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.networkOrder = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.networkOrder = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.octDomesticIndicator!=null?this.octDomesticIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.octCrossBorderIndicator!=null?this.octCrossBorderIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.aftDomesticIndicator!=null?this.aftDomesticIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.aftCrossBorderIndicator!=null?this.aftCrossBorderIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.networkID!=null?this.networkID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.networkOrder!=null?this.networkOrder:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "octDomesticIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "octCrossBorderIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "aftDomesticIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "aftCrossBorderIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "networkID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "networkOrder";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "id";
            info.namespace= "";
            if(this.id!=null)
            {
                info.setValue(this.id);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

