package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class PayerAuthEnrollReply extends AttributeContainer implements KvmSerializable
{

    
    public BigInteger reasonCode=BigInteger.ZERO;
    
    public String acsURL;
    
    public String authenticationResult;
    
    public String authenticationStatusMessage;
    
    public String cavv;
    
    public String cavvAlgorithm;
    
    public String commerceIndicator;
    
    public String eci;
    
    public String eciRaw;
    
    public String paReq;
    
    public String proxyPAN;
    
    public String xid;
    
    public String proofXML;
    
    public String ucafAuthenticationData;
    
    public String ucafCollectionIndicator;
    
    public String paresStatus;
    
    public String veresEnrolled;
    
    public String authenticationPath;
    
    public String specificationVersion;
    
    public String authenticationTransactionID;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("reasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reasonCode = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.reasonCode = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("acsURL"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.acsURL = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.acsURL = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authenticationResult"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authenticationResult = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authenticationResult = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authenticationStatusMessage"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authenticationStatusMessage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authenticationStatusMessage = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cavv"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cavv = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cavv = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cavvAlgorithm"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cavvAlgorithm = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cavvAlgorithm = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("commerceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.commerceIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.commerceIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("eci"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.eci = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.eci = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("eciRaw"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.eciRaw = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.eciRaw = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paReq"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paReq = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paReq = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("proxyPAN"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.proxyPAN = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.proxyPAN = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("xid"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.xid = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.xid = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("proofXML"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.proofXML = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.proofXML = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ucafAuthenticationData"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ucafAuthenticationData = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ucafAuthenticationData = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ucafCollectionIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ucafCollectionIndicator = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ucafCollectionIndicator = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paresStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paresStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paresStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("veresEnrolled"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.veresEnrolled = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.veresEnrolled = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authenticationPath"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authenticationPath = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authenticationPath = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("specificationVersion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.specificationVersion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.specificationVersion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("authenticationTransactionID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.authenticationTransactionID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.authenticationTransactionID = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.reasonCode!=null?this.reasonCode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.acsURL!=null?this.acsURL:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.authenticationResult!=null?this.authenticationResult:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.authenticationStatusMessage!=null?this.authenticationStatusMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.cavv!=null?this.cavv:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.cavvAlgorithm!=null?this.cavvAlgorithm:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.commerceIndicator!=null?this.commerceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.eci!=null?this.eci:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.eciRaw!=null?this.eciRaw:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.paReq!=null?this.paReq:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.proxyPAN!=null?this.proxyPAN:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.xid!=null?this.xid:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.proofXML!=null?this.proofXML:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.ucafAuthenticationData!=null?this.ucafAuthenticationData:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.ucafCollectionIndicator!=null?this.ucafCollectionIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.paresStatus!=null?this.paresStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.veresEnrolled!=null?this.veresEnrolled:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.authenticationPath!=null?this.authenticationPath:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.specificationVersion!=null?this.specificationVersion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.authenticationTransactionID!=null?this.authenticationTransactionID:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 20;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reasonCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "acsURL";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authenticationResult";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authenticationStatusMessage";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cavv";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cavvAlgorithm";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "commerceIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "eci";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "eciRaw";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paReq";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "proxyPAN";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "xid";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "proofXML";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ucafAuthenticationData";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ucafCollectionIndicator";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paresStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "veresEnrolled";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authenticationPath";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "specificationVersion";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "authenticationTransactionID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

