package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PayPalDoCaptureService extends AttributeContainer implements KvmSerializable
{

    
    public String paypalAuthorizationId;
    
    public String completeType;
    
    public String paypalEcDoPaymentRequestID;
    
    public String paypalEcDoPaymentRequestToken;
    
    public String paypalAuthorizationRequestID;
    
    public String paypalAuthorizationRequestToken;
    
    public String invoiceNumber;
    
    public String run;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("run"))
        {	
            java.lang.Object j = inObj.getAttribute("run");
            if (j != null)
            {
                run = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("paypalAuthorizationId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalAuthorizationId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalAuthorizationId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("completeType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.completeType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.completeType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalEcDoPaymentRequestID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalEcDoPaymentRequestID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalEcDoPaymentRequestID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalEcDoPaymentRequestToken"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalEcDoPaymentRequestToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalEcDoPaymentRequestToken = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalAuthorizationRequestID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalAuthorizationRequestID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalAuthorizationRequestID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalAuthorizationRequestToken"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalAuthorizationRequestToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalAuthorizationRequestToken = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("invoiceNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.invoiceNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.invoiceNumber = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.paypalAuthorizationId!=null?this.paypalAuthorizationId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.completeType!=null?this.completeType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.paypalEcDoPaymentRequestID!=null?this.paypalEcDoPaymentRequestID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.paypalEcDoPaymentRequestToken!=null?this.paypalEcDoPaymentRequestToken:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.paypalAuthorizationRequestID!=null?this.paypalAuthorizationRequestID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.paypalAuthorizationRequestToken!=null?this.paypalAuthorizationRequestToken:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.invoiceNumber!=null?this.invoiceNumber:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalAuthorizationId";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "completeType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalEcDoPaymentRequestID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalEcDoPaymentRequestToken";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalAuthorizationRequestID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalAuthorizationRequestToken";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "invoiceNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "run";
            info.namespace= "";
            if(this.run!=null)
            {
                info.setValue(this.run);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

