package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class PayPalEcGetDetailsReply extends AttributeContainer implements KvmSerializable
{

    
    public BigInteger reasonCode=BigInteger.ZERO;
    
    public String paypalToken;
    
    public String payer;
    
    public String payerId;
    
    public String payerStatus;
    
    public String payerSalutation;
    
    public String payerFirstname;
    
    public String payerMiddlename;
    
    public String payerLastname;
    
    public String payerSuffix;
    
    public String payerCountry;
    
    public String payerBusiness;
    
    public String shipToName;
    
    public String shipToAddress1;
    
    public String shipToAddress2;
    
    public String shipToCity;
    
    public String shipToState;
    
    public String shipToCountry;
    
    public String shipToZip;
    
    public String addressStatus;
    
    public String payerPhone;
    
    public String avsCode;
    
    public String street1;
    
    public String street2;
    
    public String city;
    
    public String state;
    
    public String postalCode;
    
    public String countryCode;
    
    public String countryName;
    
    public String addressID;
    
    public String errorCode;
    
    public String correlationID;
    
    public String paypalBillingAgreementAcceptedStatus;
    
    public String paypalTaxAmount;
    
    public ArrayList< Item> item =new ArrayList<Item >();
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("reasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reasonCode = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.reasonCode = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalToken"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalToken = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payer"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payer = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payer = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerSalutation"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerSalutation = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerSalutation = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerFirstname"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerFirstname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerFirstname = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerMiddlename"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerMiddlename = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerMiddlename = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerLastname"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerLastname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerLastname = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerSuffix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerSuffix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerSuffix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerBusiness"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerBusiness = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerBusiness = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToAddress1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToAddress1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToAddress1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToAddress2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToAddress2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToAddress2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToCity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToCity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToCity = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToState"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToState = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToState = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shipToZip"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shipToZip = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shipToZip = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.addressStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.addressStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("payerPhone"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.payerPhone = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.payerPhone = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("avsCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.avsCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.avsCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("city"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.city = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.city = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("state"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.state = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.state = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("postalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.postalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.postalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("countryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.countryCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.countryCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("countryName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.countryName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.countryName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.addressID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.addressID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("errorCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.errorCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.errorCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("correlationID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.correlationID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.correlationID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalBillingAgreementAcceptedStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalBillingAgreementAcceptedStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalBillingAgreementAcceptedStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalTaxAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalTaxAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalTaxAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("item"))
        {
            if(obj!=null)
            {
                if(this.item==null)
                {
                    this.item = new java.util.ArrayList< Item>();
                }
                java.lang.Object j =obj;
                Item j1= (Item)__envelope.get(j,Item.class,false);
                this.item.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.reasonCode!=null?this.reasonCode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.paypalToken!=null?this.paypalToken:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.payer!=null?this.payer:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.payerId!=null?this.payerId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.payerStatus!=null?this.payerStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.payerSalutation!=null?this.payerSalutation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.payerFirstname!=null?this.payerFirstname:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.payerMiddlename!=null?this.payerMiddlename:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.payerLastname!=null?this.payerLastname:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.payerSuffix!=null?this.payerSuffix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.payerCountry!=null?this.payerCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.payerBusiness!=null?this.payerBusiness:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.shipToName!=null?this.shipToName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.shipToAddress1!=null?this.shipToAddress1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.shipToAddress2!=null?this.shipToAddress2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.shipToCity!=null?this.shipToCity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.shipToState!=null?this.shipToState:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.shipToCountry!=null?this.shipToCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.shipToZip!=null?this.shipToZip:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.addressStatus!=null?this.addressStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.payerPhone!=null?this.payerPhone:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.avsCode!=null?this.avsCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.street1!=null?this.street1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.street2!=null?this.street2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.city!=null?this.city:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.state!=null?this.state:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.postalCode!=null?this.postalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.countryCode!=null?this.countryCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.countryName!=null?this.countryName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.addressID!=null?this.addressID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.errorCode!=null?this.errorCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.correlationID!=null?this.correlationID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.paypalBillingAgreementAcceptedStatus!=null?this.paypalBillingAgreementAcceptedStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==33)
        {
            return this.paypalTaxAmount!=null?this.paypalTaxAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=34 && propertyIndex < 34+this.item.size())
        {
            java.lang.Object item = this.item.get(propertyIndex-(34));
            return item!=null?item:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 34+item.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reasonCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalToken";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payer";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerId";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerSalutation";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerFirstname";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerMiddlename";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerLastname";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerSuffix";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerBusiness";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToAddress1";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToAddress2";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToCity";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToState";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToCountry";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shipToZip";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "addressStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "payerPhone";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "avsCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street1";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street2";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "city";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "state";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "postalCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "countryCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "countryName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "addressID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "errorCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "correlationID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalBillingAgreementAcceptedStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalTaxAmount";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex>=34 && propertyIndex < 34+this.item.size())
        {
            info.type = Item.class;
            info.name = "item";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

