package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;

public class PayPalDoRefTransactionReply extends AttributeContainer implements KvmSerializable
{

    
    public BigInteger reasonCode=BigInteger.ZERO;
    
    public String paypalBillingAgreementId;
    
    public String transactionId;
    
    public String paypalTransactionType;
    
    public String paypalPaymentType;
    
    public String paypalOrderTime;
    
    public String paypalAmount;
    
    public String currency;
    
    public String paypalTaxAmount;
    
    public String paypalExchangeRate;
    
    public String paypalPaymentStatus;
    
    public String paypalPendingReason;
    
    public String paypalReasonCode;
    
    public String errorCode;
    
    public String correlationID;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("reasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.reasonCode = new BigInteger(j.toString());
                    }
                }
                else if (obj instanceof BigInteger){
                    this.reasonCode = (BigInteger)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalBillingAgreementId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalBillingAgreementId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalBillingAgreementId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("transactionId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.transactionId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.transactionId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalTransactionType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalTransactionType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalTransactionType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalPaymentType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalPaymentType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalPaymentType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalOrderTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalOrderTime = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalOrderTime = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("currency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.currency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.currency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalTaxAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalTaxAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalTaxAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalExchangeRate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalExchangeRate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalExchangeRate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalPaymentStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalPaymentStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalPaymentStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalPendingReason"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalPendingReason = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalPendingReason = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("paypalReasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.paypalReasonCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.paypalReasonCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("errorCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.errorCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.errorCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("correlationID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.correlationID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.correlationID = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.reasonCode!=null?this.reasonCode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.paypalBillingAgreementId!=null?this.paypalBillingAgreementId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.transactionId!=null?this.transactionId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.paypalTransactionType!=null?this.paypalTransactionType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.paypalPaymentType!=null?this.paypalPaymentType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.paypalOrderTime!=null?this.paypalOrderTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.paypalAmount!=null?this.paypalAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.currency!=null?this.currency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.paypalTaxAmount!=null?this.paypalTaxAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.paypalExchangeRate!=null?this.paypalExchangeRate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.paypalPaymentStatus!=null?this.paypalPaymentStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.paypalPendingReason!=null?this.paypalPendingReason:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.paypalReasonCode!=null?this.paypalReasonCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.errorCode!=null?this.errorCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.correlationID!=null?this.correlationID:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 15;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "reasonCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalBillingAgreementId";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "transactionId";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalTransactionType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalPaymentType";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalOrderTime";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalAmount";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "currency";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalTaxAmount";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalExchangeRate";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalPaymentStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalPendingReason";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "paypalReasonCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "errorCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "correlationID";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

