package com.cencosud.scanandgo.cybersource.client;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ShipTo extends AttributeContainer implements KvmSerializable
{

    
    public String title;
    
    public String firstName;
    
    public String middleName;
    
    public String lastName;
    
    public String suffix;
    
    public String street1;
    
    public String street2;
    
    public String street3;
    
    public String street4;
    
    public String street5;
    
    public String city;
    
    public String county;
    
    public String state;
    
    public String buildingNumber;
    
    public String district;
    
    public String postalCode;
    
    public String country;
    
    public String company;
    
    public String phoneNumber;
    
    public String email;
    
    public String shippingMethod;
    
    public String name;
    
    public String id;
    
    public String addressVerificationStatus;
    
    public String notApplicable;
    
    public String immutable;
    
    public String destinationCode;
    
    public String pointOfReference;
    
    public String _default;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("title"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.title = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.title = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("firstName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.firstName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.firstName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("middleName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.middleName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.middleName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("lastName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suffix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suffix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.suffix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street3"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street3 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street3 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street4"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street4 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street4 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("street5"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.street5 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.street5 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("city"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.city = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.city = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("county"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.county = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.county = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("state"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.state = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.state = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("buildingNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.buildingNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.buildingNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("district"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.district = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.district = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("postalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.postalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.postalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("country"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.country = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.country = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("company"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.company = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.company = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("phoneNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.phoneNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.phoneNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("email"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.email = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.email = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("shippingMethod"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.shippingMethod = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.shippingMethod = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("name"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.name = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.name = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.id = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressVerificationStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.addressVerificationStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.addressVerificationStatus = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("notApplicable"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.notApplicable = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.notApplicable = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("immutable"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.immutable = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.immutable = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("destinationCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.destinationCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.destinationCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("pointOfReference"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pointOfReference = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.pointOfReference = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("default"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this._default = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this._default = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.title!=null?this.title:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.firstName!=null?this.firstName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.middleName!=null?this.middleName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.lastName!=null?this.lastName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.suffix!=null?this.suffix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.street1!=null?this.street1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.street2!=null?this.street2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.street3!=null?this.street3:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.street4!=null?this.street4:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.street5!=null?this.street5:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.city!=null?this.city:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.county!=null?this.county:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.state!=null?this.state:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.buildingNumber!=null?this.buildingNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.district!=null?this.district:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.postalCode!=null?this.postalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.country!=null?this.country:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.company!=null?this.company:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.phoneNumber!=null?this.phoneNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.email!=null?this.email:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.shippingMethod!=null?this.shippingMethod:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.name!=null?this.name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.addressVerificationStatus!=null?this.addressVerificationStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.notApplicable!=null?this.notApplicable:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.immutable!=null?this.immutable:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.destinationCode!=null?this.destinationCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.pointOfReference!=null?this.pointOfReference:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this._default!=null?this._default:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 29;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "title";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "firstName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "middleName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastName";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "suffix";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street1";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street2";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street3";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street4";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "street5";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "city";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "county";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "state";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "buildingNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "district";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "postalCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "country";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "company";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "phoneNumber";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "email";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "shippingMethod";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "name";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "id";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "addressVerificationStatus";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "notApplicable";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "immutable";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "destinationCode";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pointOfReference";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "default";
            info.namespace= "urn:schemas-cybersource-com:transaction-data-1.146";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

